# Site
name: 'Vineyard'
description: 'A Personal Blog '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'isha.niraula312@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    isha:
      name:           Isha
      site:           https://isha-niraula.github.io
      avatar:         assets/images/avatar2.jpg
      bio:            "Hi, I am Isha, the author of Vineyard. I am an 18 year old girl from Nepal.I wanted to start a blog    of my own few years ago but because of my crazy habit of procastinating that coudn’t happen.So finally here I am with my blog :my thoughts,my complains,my diaries,my culture,my world.I believe everyone must contribute something to this world.The world runs because of the small change each individual makes.So I really hope my thoughts will make a small change in  the world! I hope you like it!"
      email:          isha.niraula312@gmail.com
      twitter:        https://twitter.com/ishh_hh


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: isha
      avatar: assets/images/avatar2.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]